# Generated by Django 5.0.6 on 2024-05-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title', max_length=50)),
                ('director', models.CharField(help_text="Enter the director's name", max_length=50)),
                ('release_date', models.DateField(help_text='enter the released date')),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('ROMANCE', 'Romance'), ('FICTION', 'Fiction'), ('THRILLER', 'Thriller'), ('ANIMATION', 'Animation'), ('FANTASY', 'Fantasy'), ('DOCUMENTARY', 'Documentary'), ('OTHER', 'Other')], default='OTHER', help_text='select the genre', max_length=50)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], default=3, help_text='select the rating')),
            ],
        ),
    ]
